app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
    initial-delay: 10s
    limit: 10
  kafka-topics:
    link-updates: link-updates
  bot:
    url: ${BOT_URL:http://localhost:8080}
  sender:
    type: kafka

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/scrapper}
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
