app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
    initial-delay: 10s
    limit: 10
  kafka-topics:
    link-updates: link-updates

spring:
  application:
    name: scrapper
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
